<p>
Happy New Years and welcome to atlantica.Erenda.org a database-based website owned and operated by Vale (#198) of the Sikyon server.  We hope you'll peruse our articles, participate in the forum discussions and utilize our crafting database.
</p>  
<p>
Much of the content and articles are currently under development and are not yet online but check back frequently and we'll keep you updated as new content is added.
</p>
<p>
While you're here why don't you take this opportunity to sign up for our forums and our mailing list.
</p>
<p>
We hope to see you back soon.  From Michii, Sundance and Tomast we hope your new years were safe and fun and good luck in the coming year!
</p>