<?php $this->headScript()->appendScript("showOnLoad('crafting');")?>

<table>
	<tr><th>id</th><th>name</th><th>exp</th><th>level</th><th>workload</th><th>cost</th><th>cost/workload</th></tr>
	<tr>
		<td><?php echo $this->craftable['id'] ?></td>
		<td><?php echo $this->craftable['name'] ?></td>
		<td><?php echo $this->craftable['experience'] ?></td>
		<td style="text-align:right"><?php echo $this->craftable['level'] ?></td>
		<td style="text-align:right"><?php echo $this->craftable['workload'] ?></td>
		<td style="text-align:right"><?php echo $this->craftable['cost'] ?><?php if(!$this->craftable['actualcost']) { echo '*'; }?></td>
		<td style="text-align:right"><?php echo number_format(($this->craftable['cost']/$this->craftable['workload']),3) ?></td>
	</tr>
</table>

<table>
<tr><th>id</th><th colspan="2">name</th><th>cost</th><th>amount</th><th>total</th></tr>
<?php foreach($this->craftable['resources'] as $resource) {?>
	<tr>
		<td><?php echo $resource['id'] ?></td>
		<td colspan="2">
			<a href="<?php echo $this->url(array('controller'=>'crafting', 'action'=>'resource'), 'default', true) ?>/<?php echo $resource['id'] ?>">
				<?php echo $resource['name'] ?>
			</a>
		</td>
		<td style="text-align:right"><?php echo $resource['full_cost'] ?></td>
		<td style="text-align:right"><?php echo $resource['amount'] ?></td>
		<td style="text-align:right"><?php echo ($resource['full_cost'] * $resource['amount']) ?></td>
	</tr>
	<?php 
	if($resource['craftable'] == 1) { 
		foreach($resource['components'] as $res_comp) {
	?>
	<tr>
		<td><?php echo $res_comp['id'] ?></td>
		<td style="width:10px;"></td>
		<td colspan="1">
			<a href="<?php echo $this->url(array('controller'=>'crafting', 'action'=>'resource'), 'default', true) ?>/<?php echo $res_comp['id'] ?>">
				<?php echo $res_comp['name'] ?>
			</a>
		</td>
		<td style="text-align:right"><?php echo $res_comp['fixedprice'] ?></td>
		<td style="text-align:right"><?php echo $res_comp['amount'] ?></td>
		<td style="text-align:right"><?php echo ($res_comp['full_cost']) ?></td>
	</tr>		
	<?php 
		}
	}?>	
<?php }?>
</table>