<a href="<?php echo $this->url(array('controller'=>'crafting', 'action'=>'exportresources'), 'default', true) ?>">export</a>
<br />
<table>
<form method="post" action="<?php echo $this->url(array('controller'=>'crafting', 'action'=>'addresource'), 'default', true) ?>">
<label for="name">Name: <input name="name" /> </label><br />
<label for="fixedprice">Price: <input name="fixedprice" /> </label><br />
<input type="submit" value="Add" />
</form>
<tr><th>id</th><th>name</th><th>fixed price</th>
<?php foreach ($this->resources as $resource) { ?>
	<tr>
		<td><?php echo $resource['id'] ?></td>
		<td><?php echo $resource['name'] ?></td>
		<td><?php echo $resource['fixedprice'] ?></td>
	</tr>
<?php } ?>
</table>