<?php $this->headScript()->appendScript("showOnLoad('crafting');")?>
<table>
<tr><th>id</th><th>name</th><th>fixed price</th>
	<tr>
		<td><?php echo $this->resource['id'] ?></td>
		<td><?php echo $this->resource['name'] ?></td>
		<td><?php echo $this->resource['fixedprice'] ?></td>
	</tr>
</table>

<table>
<tr><th>id</th><th>name</th><th>exp</th><th>level</th><th>workload</th><th>cost</th><th>cost/workload</th></tr>
<?php foreach ($this->resource['craftables'] as $craftable) { ?>
	<tr>
		<td><?php echo $craftable['id'] ?></td>
		<td>
			<a href="<?php echo $this->url(array('controller'=>'crafting', 'action'=>'craftable'), 'default', true) ?>/<?php echo $craftable['id'] ?>">
				<?php echo $craftable['name'] ?>
			</a>
		</td>
		<td><?php echo $craftable['experience'] ?></td>
		<td><?php echo $craftable['level'] ?></td>
		<td style="text-align:right"><?php echo $craftable['workload'] ?></td>
		<td style="text-align:right"><?php echo $craftable['cost'] ?><?php if(!$craftable['actualcost']) { echo '*'; }?></td>
		<td style="text-align:right"><?php echo number_format(($craftable['cost']/$craftable['workload']),3) ?></td>
	</tr>
<?php }?>
</table>