<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head><title><?php echo $this->title?></title>

<script type="text/javascript" src="/js/Mochikit/Mochikit.js"></script>
<script type="text/javascript" src="/js/erenda_lib.js"></script>

<!--[if lt IE 7.]>
<script defer type="text/javascript" src="pngfix.js"></script>
<![endif]-->

<?php $this->headLink()->prependStylesheet('/css/mainstyle.css'); ?>
<?php echo $this->headLink(); ?>

<?php echo $this->headScript(); ?>
</head>
<body>


<div id="pagewrapper">

<div id ="pageheader"> <div id="top"><div id="topmenu">
<a href=""><img src="/images/common/top_blank.gif" width="70" border="0"></a>
<a href="/"><img id="top_home" src="/images/common/top_homeA.png" border="0" onMouseover="document.top_home.src='/images/common/top_homeB.png';" onMouseout="document.top_home.src='/images/common/top_homeA.png';"></a>
<a href=""><img id="top_links" src="/images/common/top_linksA.png" border="0" onMouseover="document.top_links.src='/images/common/top_linksB.png';" onMouseout="document.top_links.src='/images/common/top_linksA.png';"></a>
<a href=""><img id="top_contact" src="/images/common/top_contactA.png" border="0" onMouseover="document.top_contact.src='/images/common/top_contactB.png';" onMouseout="document.top_contact.src='/images/common/top_contactA.png';"></a>
<a href=""><img id="top_forum" src="/images/common/top_forumA.png" border="0" onMouseover="document.top_forum.src='/images/common/top_forumB.png';" onMouseout="document.top_forum.src='/images/common/top_forumA.png';"></a>
<a href=""><img id="top_about" src="/images/common/top_aboutA.png" border="0" onMouseover="document.top_about.src='/images/common/top_aboutB.png';" onMouseout="document.top_about.src='/images/common/top_aboutA.png';"></a>
</div></div></div><br>

<div id="content">
<div id="sidemenu">
<span onClick="javascript:toggleVisible('news');"><img src="/images/common/menu_news.png"> </span><br>
<div id="news" name="news"  style="padding-left:15px;">
<b>Coming Soon!!</b><br>
<span class="comingsooncontent">Front Page News</span><br>
<span class="comingsooncontent">Report a News Story</span><br>
<!--
<a href="">Archived News</a><br>
<a href="">Report a News Story</a><br>
<a href="">Server Status</a><br>
<a href="">Planned updates and downtimes</a><br>
-->
</div>
<p>


<span onClick="javascript:toggleVisible('game');"><img src="/images/common/menu_game.png"></span><br>
<div id="game" class="invisible"  style="padding-left:15px;">
<a href="<?php echo $this->url(array('controller'=>'game', 'action'=>'mercenaries'), 'default', true) ?>">Mercenaries</a><br>
<b>Coming Soon!!</b>
<br><span class="comingsooncontent">Merc Quests</span><br>
<span class="comingsooncontent">Level FAQ</span><br>
<!--<a href="">Skills</a><br>
<a href="">Classes</a><br>

<a href="">Quest NPC</a><br>
<a href="">Merc title</a><br>

-->
</div>
<p>

<span onClick="javascript:toggleVisible('npcinfo');"><img src="/images/common/menu_npc.png"></span><br>
<div id="npcinfo" class="invisible"  style="padding-left:15px;">
<b>Coming Soon!!</b><br>
<span class="comingsooncontent">Livingston</span><br>
<span class="comingsooncontent">Goncourt</span><br>
<!--<span class="comingsooncontent">Hui Chao</a>  <br>
<a href="">Howard  </a>-->
</div>
<p>
<span onClick="javascript:toggleVisible('quests'); "onClick="javascript:toggleVisible('quests');"><img src="/images/common/menu_quests.png"></span><br>
<div id="quests" class="invisible"  style="padding-left:15px;">
<b>Coming Soon!!</b><br>
<span class="comingsooncontent">Main: </span><br>
<span class="comingsooncontent">Sidequests:</span><br>
</div>
<p>
<span onClick="javascript:toggleVisible('iteminfo');"><img src="/images/common/menu_item.png"><img src="/images/common/menu_items.png"></span><br>
<div id="iteminfo" class="invisible"  style="padding-left:15px;">
<b>Coming Soon!!</b><br>
<span class="comingsooncontent">Equipment Info</span><br>
<!--<a href="">Enchanting FAQ</a><br> 
<a href="">Enhancing</a><br>-->
<span class="comingsooncontent">Material Boxes</span><br>
</div>
<p>
<span onClick="javascript:toggleVisible('location');"><img src="/images/common/menu_locations.png"></span><br>
<div id="location" class="invisible"  style="padding-left:15px;">
<b>Coming Soon!!</b><br>
<span class="comingsooncontent">Dungeons</span>br>
<!-- <a href="">Maps</a>--><br>
<span class="comingsooncontent">Towns</span><p>
</div>
<p>
<span onClick="javascript:toggleVisible('monsters');"><img src="/images/common/menu_monsters.png"></span><br>
<div id="monsters" class="invisible"  style="padding-left:15px;">
<b>Coming Soon!!</b><br>
<!-- <a href="">Special Mobs</a><br>-->
<span class="comingsooncontent">Monster Info FAQ</span><br>
</div>
<p>
<span onClick="javascript:toggleVisible('rome');"><img src="/images/common/menu_rome.png"></span><br>
<div id="rome" class="invisible"  style="padding-left:15px;">
<b>Coming Soon!!</b><br>
<span class="comingsooncontent">Vulcanus </span><br>
<span class="comingsooncontent">Gambler De Mere</span><br>
<span class="comingsooncontent">Pointry</span><br>
<!-- <a href="">Sothesby </a><br>
<a href="">Maximus</a> <br>-->
</div>
<p>
<span onClick="javascript:toggleVisible('crafting');"><img src="/images/common/menu_crafting.png"></span><br>
<div id="crafting" class="invisible"  style="padding-left:15px;">
<b>Coming Soon!!</b><br>

<a href="<?php echo $this->url(array('controller'=>'crafting', 'action'=>''), 'default', true) ?>">Formulas</a><br>
<a href="<?php echo $this->url(array('controller'=>'crafting', 'action'=>'resources'), 'default', true) ?>">Resources</a><br>
</div>
<p>
<span onClick="javascript:toggleVisible('guilds');"><img src="/images/common/menu_guilds.png"></span><br>
<div id="guilds" class="invisible"  style="padding-left:15px;">
<b>Coming Soon!!</b><br>
<span class="comingsooncontent">Guild FAQ</span> <br>
<!-- Guild List by Server<br>-->
<a href="<?php echo $this->url(array('controller'=>'guilds', 'action'=>'links'), 'default', true)?>">Links</a><br />
</div>
<p>
<span onClick="javascript:toggleVisible('freeleague');"><img src="/images/common/menu_freeleague.png"></span><br>
<div id="freeleague" class="invisible"  style="padding-left:15px;">
<b>Coming Soon!!</b><br>
 <!--Free League Formations<br>-->
<span class="comingsooncontent">Free League FAQ<p></span>
</div>
<p>
<span onClick="javascript:toggleVisible('market');"><img src="/images/common/menu_market.png"></span><br>
<div id="market" class="invisible" style="padding-left:15px;">
<b>Coming Soon!!</b><br>
<span class="comingsooncontent">Products and Profits<br>
Supply and Demand basics</span></div> 
<p>

<span onClick="javascript:toggleVisible('strat');"><img src="/images/common/menu_strategies.png"></span><br>
<div id="strat" class="invisible"  style="padding-left:15px;">
<b>Coming Soon!!</b><br>
<span class="comingsooncontent">Tips & Tricks<br></span>
<!-- 
Mercenaries</br>
Did you know…<br>--></div>
</div>
<?php echo $this->layout()->content ?>
</div>
</div>

</div>
</body></html>

