<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<title>Atlantica . Erenda</title>
	<?php echo $this->headLink()->appendStylesheet('/css/global.css') ?>
</head>
<body>
	<div id="header" style="background-color: #eee; height: 30px;">
		<div id="header-logo" style="float: left">
			<b>Atlantica . Erenda</b>
		</div>
		<div id="header-navigation" style="float: right">
			<a href="<?php echo $this->url(array('controller'=>'login'), 'default', true) ?>">Login</a>
		</div>
	</div>
	
	<?php echo $this->layout()->content ?>
	
</body>
</html>