
insert into news (title, content, created_date)
Values ('Title: Ipsum', 
'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Sed gravida malesuada erat. Donec sed lectus. Aliquam bibendum fermentum dolor. Curabitur nisl nunc, porttitor et, convallis vitae, fringilla id, lacus. Etiam tempor rutrum turpis. Fusce sed velit. Aenean justo. Aenean nisi mauris, porttitor ac, posuere a, semper eget, lectus. Morbi pretium, odio ac gravida iaculis, enim orci fermentum odio, ac faucibus ligula eros vel diam. Integer volutpat varius mi. Vivamus sapien lorem, tincidunt quis, fermentum a, commodo vitae, pede.

Integer imperdiet felis vitae enim. Donec ac mi. Phasellus id metus. Proin est. Ut vitae metus vitae nibh sollicitudin suscipit. Morbi pellentesque, sapien et luctus molestie, nisl turpis tincidunt lacus, a ullamcorper diam felis sed risus. Sed porttitor quam. Quisque mollis arcu at mi tincidunt molestie. Curabitur imperdiet pharetra odio. Pellentesque euismod rutrum felis. Duis et arcu. Vestibulum viverra ante et mi. Nulla interdum neque sed lorem. Vestibulum blandit augue a dolor. Nam lorem felis, pellentesque nec, molestie eu, sagittis ac, ante. Nulla facilisi.

Aliquam et lectus ut ante sodales gravida. Nam mauris turpis, mollis vulputate, lobortis faucibus, fringilla non, lacus. Pellentesque vitae tortor. Mauris mollis faucibus justo. Sed at lacus ut est gravida aliquet. Curabitur blandit, lectus eu venenatis imperdiet, metus orci dictum arcu, sed viverra elit felis non lorem. Proin orci. Aenean consequat, tortor quis malesuada vehicula, enim elit pellentesque metus, ac bibendum eros metus ac augue. Morbi placerat tempor lacus. In nec nulla sed augue tincidunt suscipit. Morbi sit amet nulla eget eros rhoncus pulvinar. Curabitur sodales tellus id libero. In eu dui. Phasellus ultricies sollicitudin quam. Nulla nec neque. Vestibulum elementum dolor.

Vestibulum eu felis eget metus sollicitudin varius. Duis nibh. Sed risus. Suspendisse nec mi eget enim feugiat tempor. Mauris neque. Fusce diam nisl, volutpat quis, fringilla sit amet, lacinia pellentesque, erat. Mauris malesuada accumsan ante. Pellentesque vel lorem. Suspendisse potenti. Curabitur a nisl et augue egestas semper. Suspendisse in nulla. Nullam eros est, dictum id, porttitor nec, convallis eget, augue. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.

Donec congue tristique nulla. Sed justo. Morbi luctus, ante a pellentesque lobortis, pede metus cursus erat, sit amet suscipit erat orci non urna. Donec venenatis eleifend libero. Sed accumsan volutpat lectus. Nam eleifend. Donec semper ultricies justo. In auctor lacus non massa fermentum ullamcorper. Suspendisse pulvinar metus in ligula. Sed tempor eros et nunc. Maecenas nec purus. Nunc porta enim nec neque. Praesent quis odio at nulla vulputate rhoncus. Fusce tristique mollis justo.',
'2008-11-16 18:14:00');

insert into mercenary values ('swordsman', 'Swordsman', 340, 240, 400, 130, 250, 125, null);
insert into mercenary values ('viking', 'Viking', 330, 110, 280, 140, 310, -50, null);